### PR TITLE
Make newestCommentTime optional

### PR DESCRIPTION
**Pull request by micahmo**
I've been getting nulls in the `newestCommentTime` field. I couldn't find anything in the changelog saying it was removed, but I figured it couldn't hurt to make it nullable to play it safe. Now voyager.lemmy.ml loads for me again.

image

### CODE REVIEW

**Comment by hjiangsu** [comment]
Hmm, there seems to be more changes potentially present here which relate to `PostAggregates` which have been removed: https://github.com/LemmyNet/lemmy-js-client/commit/24eed9e7be7212ad7ac54a7fa15526ac14b7b566

If this attribute is not being used in Thunder (would have to double check), should we just remove them entirely? Alternatively, we could make them optional, and mark them as deprecated so that we can clean up the API code in the future if we ever drop support for 0.18.x versions

**Comment by micahmo** [comment]
> Hmm, there seems to be more changes potentially present here which relate to `PostAggregates` which have been removed: [LemmyNet/lemmy-js-client@24eed9e](https://github.com/LemmyNet/lemmy-js-client/commit/24eed9e7be7212ad7ac54a7fa15526ac14b7b566)

Good catch, I missed those! Interesting that I didn't hit any others. Maybe the other fields weren't even in our models.

> If this attribute is not being used in Thunder (would have to double check)

I don't think it is, otherwise I probably would've run into some build issues after changing the nullability.

> should we just remove them entirely?

That makes sense to me! It won't hurt anything that currently exists, and it will also prevent us from building a new feature around something that's going away. Maybe we could leave it in, commented out, with a comment explaining why (just to prevent us from ever adding it back in by mistake).

> Alternatively, we could make them optional, and mark them as deprecated

Out of curiosity, what would this look like? What do you mean by mark as optional?

P.S. Whatever we decide here, we should do the same for `PersonSafe.admin`, because I also marked that as nullable for the same reason.

https://github.com/thunder-app/lemmy_api_client/pull/4/files#diff-27a77cc09ea7733233a3579b24d13c74c63c5c12a35ee6c71ac4ee59b46a001eR27-R29

**Comment by hjiangsu** [comment]
> Out of curiosity, what would this look like? What do you mean by mark as optional?

I was thinking it could look something like this

Original:
```dart
const factory CreateComment({
    required String content,
    int? parentId,
    required int postId,
    String? formId,
    required String auth,
  }) = _CreateComment;

```

Modified (notice how I made `auth` optional here)
```dart
const factory CreateComment({
    required String content,
    int? parentId,
    required int postId,
    @deprecated String? formId,
    @deprecated String? auth,
  }) = _CreateComment;

```

On a side note, I was looking through all the API endpoints and comparing them to what's officially available, and it seems like we're not in parity with the lemmy-js-client for both endpoints and parameters (for 0.18.x and 0.19.x). 

I was thinking maybe I can work on a full refactor of all the endpoints and models here, so that we can
- Organize the codebase a bit better to separate the endpoints based on the path (e.g., `/user`, `/community`, etc) instead of how it is right now
- Reach full parity of 0.18.x and 0.19.x endpoints and parameters. I would then mark all the fields that are about to be removed in 0.19.x as deprecated and optional like the example above

This refactor might affect some naming of the classes that would have to be fixed in Thunder, but it also means it would be easier to handle changes and deprecations in the future as the class names and models would match up with the interfaces on lemmy-js-client

**Comment by micahmo** [comment]
Ok I gotcha now. Instead of just making the field nullable, you would also remove `required` (which makes sense for nullable fields in general I'd say).

> I was thinking maybe I can work on a full refactor of all the endpoints and models here

That sounds great!

For now, I've done as you suggested for `newestCommentTime`, `newestCommentTimeNecro` and `admin`, so we can merge that or just wait for your refactor.

P.S. Now I'm hitting another issue logging into 0.19. Seems like the type of the subject field in the JWT has changed from int to string, so we'll have to figure out how to handle that. 😊

**Comment by hjiangsu** [comment]
Just wanted to provide an update - I've created an initial draft PR for the refactor. It's a substantial change with some breaking changes (as mentioned in the PR description) https://github.com/thunder-app/lemmy_api_client/pull/10

I'm hoping to get another draft PR up for Thunder to handle all the breaking changes involved in that PR. That PR includes most, if not all the changes described here: https://github.com/LemmyNet/lemmy-js-client/compare/0.18.3-rc.3...0.19.0-rc.14 and should hopefully be fully compatible with 0.18.x and 0.19.0-rc.14

I'll hold off on merging this PR in as the refactor might make it irrelevant. However, if you do want me to still include this in, let me know and I can do it in the meantime!

**Comment by micahmo** [comment]
That's awesome! And no hurry, I'm happy to wait for that one.

**Comment by hjiangsu** [comment]
I'll close this in favour of #10 - let me know if there are any questions about this

**Pull request closed without merging**
