### PR TITLE
Match API parity with 0.19.0-alpha.16

### PR DESCRIPTION
**Pull request by hjiangsu**
This PR is to match parity up to 0.19.0-alpha.16: https://github.com/LemmyNet/lemmy-js-client/compare/0.19.0-rc.14...0.19.0-alpha.16. This will remain a draft until changes are made on Thunder to allow for the changes in the responses.

A few notes:
- There are quite a few API changes whose responses have changed. The solution to this was described in [this discussion](https://github.com/thunder-app/lemmy_api_client/discussions/12#discussioncomment-7473870)
- A few attributes related to `post_score` and `comment_score` has been removed, which is an issue since Thunder has the option to show those scores.

### CODE REVIEW

**Comment by micahmo** [comment]
Is `score` essentially just `upvotes - downvotes`? If so, could we maintain that behavior via an extension? Or maybe if Lemmy is moving away from displaying that, we should too.

**Comment by hjiangsu** [comment]
Ahh, I should clarify: `post_score` and `comment_score` are on `PersonAggregates`. This means that "karma" is essentially being removed from the API.

From what I can see in [this discussion](https://github.com/LemmyNet/lemmy/issues/3393#issuecomment-1779400639), it seems like the best approach here moving forward is to not display these scores at all within Thunder starting in 0.19.x.

**Comment by micahmo** [comment]
Sounds good. It was already optional and off by default in Thunder, so hopefully not too many people will miss it. 😊

**Comment by hjiangsu** [comment]
I'll merge this in now and create a PR for Thunder with the required changes!

**Pull request merged**
